repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/.*\.(ts|tsx|js|jsx|json|css|md|html)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.36.0
    hooks:
      - id: eslint
        name: eslint (frontend)
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        args:
          - --config
          - frontend/eslint.config.js
        additional_dependencies:
          - eslint@9.36.0
          - '@eslint/js@9.36.0'
          - eslint-plugin-react-hooks@5.2.0
          - eslint-plugin-react-refresh@0.4.22
          - globals@16.4.0
          - typescript@5.9.3
          - typescript-eslint@8.45.0
