# Generated by Django 4.2.24 on 2025-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell_ai_insights', '0002_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
