# Generated by Django 4.2.24 on 2025-10-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell_ai_insights', '0004_run_output_dir_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='indexed_at',
        ),
        migrations.RemoveField(
            model_name='run',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='run',
            name='normalized_context',
        ),
    ]
