# Generated by Django 4.2.24 on 2025-10-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell_ai_insights', '0006_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='plot_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='table_url',
        ),
    ]
