# Generated by Django 4.2.24 on 2025-10-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell_ai_insights', '0007_remove_artifact_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
