# Generated by Django 4.2.24 on 2025-10-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlecell_ai_insights', '0008_add_run_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='confidence_explanation',
            field=models.TextField(blank=True),
        ),
    ]
