version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image with registry $ECR_REGISTRY...
      - docker build --build-arg REGISTRY=$ECR_REGISTRY -f infrastructure/docker/backend/Dockerfile -t $ECR_BACKEND_REPOSITORY:latest -t $ECR_BACKEND_REPOSITORY:$IMAGE_TAG .
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_BACKEND_REPOSITORY:latest
      - docker push $ECR_BACKEND_REPOSITORY:$IMAGE_TAG
      - echo Writing image definitions file...

artifacts:
  files:
    - imagedefinitions.json
